# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/web-app-template',
                'doc_host': 'https://Accessible-Data-and-Code.github.io',
                'git_url': 'https://github.com/Accessible-Data-and-Code/web-app-template',
                'lib_path': 'web_app_template'},
  'syms': {'web_app_template\\core': {'web_app_template\\core.foo': ('manfiles.html#foo', 'web_app_template\\core.py')}}}